### ISSUE TITLE
Please upload AppImage to GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [Sriep/Bezique#1]
Please upload the AppImage to GitHub Releases, thank you.

**Comment by Sriep** [comment]
I am confused. What is 'GitHub Releases', and why should I upload an AppImage?

**Comment by probonopd** [comment]
This is GitHub Releases: https://github.com/Sriep/Bezique/releases

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/) central directory of available AppImages

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

**Comment by Sriep** [comment]
Hi

There is a Linux AppImage on a release page

https://github.com/Sriep/Bezique/releases
https://github.com/Sriep/Bezique/releases/download/1.0.1/BeziqueLinux.AppImage

**Comment by probonopd** [comment]
Thank you.
